version: '3'

services:
      
  cmip6_book:
    image: httpd:2.4.51
    container_name: cmip6_book
    volumes:
      - ${PWD}/_build/html:/usr/local/apache2/htdocs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - "traefik.http.routers.cmip6_book.rule=Host(`hub.eoastest.xyz`) && PathPrefix(`/cmip6`)"
      - traefik.http.routers.cmip6_book.tls=true
      - traefik.http.routers.cmip6_book.tls.certresolver=lets-encrypt
      - traefik.http.routers.cmip6_book.service=cmip6_book
      - traefik.http.services.cmip6_book.loadbalancer.server.port=80
      - "traefik.http.routers.cmip6_book.middlewares=chain-strip@file"
    restart: on-failure
    networks:
      - proxy_aug07
      
#https://community.traefik.io/t/middleware-to-add-the-if-needed/1895/19      

  plot_dir:
    image: httpd:2.4.51
    container_name: plot_dir
    volumes:
      - ${PWD}/plot_dir:/usr/local/apache2/htdocs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - "traefik.http.routers.plot_dir.rule=Host(`plots.eoastest.xyz`)" 
      - traefik.http.routers.plot_dir.tls=true
      - traefik.http.routers.plot_dir.tls.certresolver=lets-encrypt
      - traefik.http.routers.plot_dir.service=plot_dir
      - traefik.http.services.plot_dir.loadbalancer.server.port=80

    restart: on-failure
    networks:
      - proxy_aug07

      
networks:
    proxy_aug07:
      external: true

# https://iceburn.medium.com/reverse-proxy-in-traefik-with-subdirectories-eef4261939e
